// Exercices lire le tableau de la fin au debut.


// const animals = ["lion", "pangolim", "zebra", "dog", "cat", "bird"];
// console.log(animals)
// for (let i =  animals.length -1 ; i >=0; i--) {
//     const element =    animals[i];
// {console.log.toString((i)) }  
// }
//  console.log(animals.reverse())

// Exercices faire une boucle for pour avoir le nom et prenom sur la console.

// const users = [
//     {
//       firstName: "Vito",
//       lastName: "Corleone",
//     },
//     {
//       firstName: "William",
//       lastName: "Wallace",
//     },
//     {
//       firstName: "Harry",
//       lastName: "Potter",
//     },
//     {
//       firstName: "Amadeus",
//       lastName: "Mozart",
//     },
//     {
//       firstName: "Barack",
//       lastName: "Obama",
//     },
//   ];
//   for (let i = 0;   i < users.length; i++)  {
   
//     console.log(" m'y name is ",users[i].firstName, users[i].lastName ); }



